# Generated by Django 4.1.5 on 2023-01-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_room_avail_space"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="avail_space",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
